export const skills = [
  {
    skill_name: "HTML",
    Image: "/assets/skills/html.png",
    width: 64,
    height: 64,
    alt: "Html Icon",
  },
  {
    skill_name: "CSS",
    Image: "/assets/skills/css.png",
    width: 64,
    height: 64,
    alt: "Css Icon",
  },
  {
    skill_name: "JavaScript",
    Image: "/assets/skills/javascript.png",
    width: 64,
    height: 64,
    alt: "JavaScript Icon",
  },
  {
    skill_name: "TypeScript",
    Image: "/assets/skills/ts.png",
    width: 64,
    height: 64,
    alt: "TypeScript Icon",
  },
  {
    skill_name: "React.Js",
    Image: "/assets/skills/react.png",
    width: 64,
    height: 64,
    alt: "React Icon",
  },
  {
    skill_name: "Redux.Js",
    Image: "/assets/skills/redux.svg",
    width: 64,
    height: 64,
    alt: "ReduxJs Icon",
  },
  {
    skill_name: "React Query",
    Image: "/assets/skills/reactquery.png",
    width: 70,
    height: 64,
    alt: "React Query Icon",
  },
  {
    skill_name: "Github",
    Image: "/assets/skills/github.png",
    width: 64,
    height: 64,
    alt: "Github Icon",
  },
  {
    skill_name: "Tailwind Css",
    Image: "/assets/skills/tailwind.png",
    width: 64,
    height: 64,
    alt: "Tailwind Icon",
  },
  {
    skill_name: "Material UI",
    Image: "/assets/skills/mui.png",
    width: 64,
    height: 64,
    alt: "Material UI Icon",
  },
  {
    skill_name: "Next.js",
    Image: "/assets/skills/nextjs.png",
    width: 64,
    height: 64,
    alt: "Next.js Icon",
  },
  {
    skill_name: "NextAuth.Js",
    Image: "/assets/skills/nextauth.png",
    width: 64,
    height: 64,
    alt: "Next Auth Js Icon",
  },
  {
    skill_name: "Framer Motion",
    Image: "/assets/skills/framer.png",
    width: 64,
    height: 64,
    alt: "Framer Motion Icon",
  },
  {
    skill_name: "Figma",
    Image: "/assets/skills/figma.png",
    width: 43,
    height: 64,
    alt: "Figma Icon",
  },
  {
    skill_name: "shadcn/ui",
    Image: "/assets/skills/shadcn.png",
    width: 64,
    height: 64,
    alt: "shadcn/ui Icon",
  },
  {
    skill_name: "Node.js",
    Image: "/assets/skills/node-js.png",
    width: 55,
    height: 64,
    alt: "Node.js Icon",
  },
];
export const projects = [
  {
    project_name: "My Portfolio",
    description:"This is my portfolio, I am using Next.js and Tailwind CSS. I am using Framer Motion for animation and Figma for design.",
    src: "/projects/portfolio.png",
    url: "https://ahmedwagih-d6ca1dh82-ahmewagihs-projects.vercel.app/",
    github: "https://github.com/AhmeWagih/portfolio-2",
    tags: ["Next.js , ","React ,", "Tailwind CSS , ", "Framer Motion"],
    width: 550,
    height: 300,
    alt: "My Portfolio",
  },
  {
    project_name: "Youtube Clone",
    description:
      " Developed a YouTube clone application using React and Tailwind CSS, integrating it with YouTube’s API to fetch and display videos, enabling users to search and watch videos seamlessly.",
    src: "/projects/youtubeclone.png",
    url: "https://youtube-clone-eight-nu.vercel.app/",
    github: "https://github.com/AhmeWagih/youtube-clone",
    tags: ["React , ", "Tailwind CSS , ", "Rapid API"],
    width: 550,
    height: 300,
    alt: "Youtube Clone",
  },
  {
    project_name: "E-Commerce App",
    description:
      " Built an e-commerce application using React and ReactRedux, allowing users to browse, select, and purchase items conveniently.",
    src: "/projects/E-commerce.png",
    url: "https://e-commerce-app-inky-gamma.vercel.app/",
    github: "https://github.com/AhmeWagih/e-commerce-app",
    tags: ["React , ", "Redux , ", "Bootstrap "],
    width: 550,
    height: 300,
    alt: "E-Commerce App",
  },
  {
    project_name: "CRUD App",
    description:
      " Developed a YouTube clone application using React and Tailwind CSS, integrating it with YouTube’s API to fetch and display videos, enabling users to search and watch videos seamlessly.",
    src: "/projects/crudapp.png",
    url: "https://curd-app-three.vercel.app/",
    github: "https://github.com/AhmeWagih/Curd_App",
    tags: ["React , ", "Redux , ", "Bootstrap "],
    width: 550,
    height: 300,
    alt: "CRUD App",
  },
  {
    project_name: "Nike Website",
    description:
      " Simple website application using React and Tailwind CSS.",
    src: "/projects/nike.png",
    url: "https://app-landing-page-using-tailwind.vercel.app/",
    github: "https://github.com/AhmeWagih/AppLandingPage_UsingTailwind",
    tags: ["React , ", "Tailwind CSS"],
    width: 550,
    height: 300,
    alt: "Nike Website",
  },
  {
    project_name: "Movie App",
    description:
      "This is my portfolio website. It is a React project. I have used Next.js, React, Tailwind and Framer Motion.",
    src: "/projects/movieapp.png",
    url: "https://movie-app-one-peach.vercel.app/",
    github: "https://github.com/AhmeWagih/movie-app",
    tags: ["React , ", "Tailwind CSS "],
    width: 550,
    height: 300,
    alt: "Movie App",
  },
  {
    project_name: "Bondi Website",
    description:
      "Responsive Website Using HTML , CSS , JavaScript and Bootstrap 5",
    src: "/projects/bondi.png",
    url: "https://responsive-website-using-bootstrap-5.vercel.app/",
    github: "https://github.com/AhmeWagih/Responsive-Website-Using-Bootstrap-5",
    tags: ["HTML , ", "CSS , "," JavaScript ,"," Bootstrap"],
    width: 550,
    height: 300,
    alt: "Bondi Website",
  },
  {
    project_name: "Wego Dashboard",
    description:
      "Responsive Website Using HTML , CSS",
    src: "/projects/design4.png",
    url: "https://html-and-css-template-four-seven.vercel.app/",
    github: "https://github.com/AhmeWagih/HTML_and_CSS_template_Four",
    tags: ["HTML , ", "CSS "],
    width: 550,
    height: 300,
    alt: "Wego Dashboard",
  },
  {
    project_name: "Wego World",
    description:
      "Responsive Website Using HTML , CSS",
    src: "/projects/design3.png",
    url: "https://html-and-css-template-three.vercel.app/",
    github: "https://github.com/AhmeWagih/HTML_and_CSS_template_Three",
    tags: ["HTML , ", "CSS "],
    width: 550,
    height: 300,
    alt: "Wego World",
  },
  {
    project_name: "Kasper Website",
    description:
      "Responsive Website Using HTML , CSS",
    src: "/projects/design2.png",
    url: "https://ahmewagih.github.io/HTML_and_CSS_template_two/",
    github: "https://github.com/AhmeWagih/HTML_and_CSS_template_two",
    tags: ["HTML , ", "CSS "],
    width: 550,
    height: 300,
    alt: "Kasper Website",
  },
  {
    project_name: "Leon Website",
    description:
      "Responsive Website Using HTML , CSS",
    src: "/projects/design1.png",
    url: "https://ahmewagih.github.io/HTML_and_CSS_template_One/",
    github: "https://github.com/AhmeWagih/HTML_and_CSS_template_One",
    tags: ["HTML , ", "CSS "],
    width: 550,
    height: 300,
    alt: "Leon Website",
  },
  {
    project_name: "Quiz App",
    description:
      "Quiz App Using HTML , CSS and JavaScript",
    src: "/projects/quizapp.png",
    url: "https://ahmewagih.github.io/Quiz_App/",
    github: "https://github.com/AhmeWagih/Quiz_App",
    tags: ["HTML , ", "CSS ,"," JavaScript "],
    width: 550,
    height: 300,
    alt: "Quiz App",
  },
  {
    project_name: "Memory Game",
    description:
      "Memory Game Using HTML , CSS and JavaScript",
    src: "/projects/memorygame.png",
    url: "https://ahmewagih.github.io/Memory_Game/",
    github: "https://github.com/AhmeWagih/Memory_Game",
    tags: ["HTML , ", "CSS ,"," JavaScript "],
    width: 550,
    height: 300,
    alt: "Memory Game",
  },
  {
    project_name: "Hangman Game",
    description:
      "Hangman Game Using HTML , CSS and JavaScript",
    src: "/projects/hangman.png",
    url: "https://ahmewagih.github.io/Hangman_Game/",
    github: "https://github.com/AhmeWagih/Hangman_Game",
    tags: ["HTML , ", "CSS ,"," JavaScript "],
    width: 550,
    height: 300,
    alt: "Hangman Game",
  },
  // {
  //   project_name: "ToDo App",
  //   description:
  //     "ToDo App Using HTML , CSS and JavaScript",
  //   src: "/projects/todo.png",
  //   url: "https://ahmewagih.github.io/ToDo_App/",
  //   github: "https://github.com/AhmeWagih/ToDo_App",
  //   tags: ["HTML , ", "CSS ,"," JavaScript "],
  //   width: 550,
  //   height: 300,
  //   alt: "ToDo App",
  // },
];
